project_id = "aarnfihphqhwvwcqgoc"

[functions.generate-movie-outline]
verify_jwt = false

[functions.generate-movie-scenes]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.wavespeed-video]
verify_jwt = false

[functions.openai-tts]
verify_jwt = false
