project_id = "aarnfihphqhwvwwcqgoc"

[functions.multi-voice-tts]
verify_jwt = false

[functions.generate-story-bible]
verify_jwt = false

[functions.generate-movie-outline]
verify_jwt = false

[functions.generate-movie-scenes]
verify_jwt = false

[functions.generate-scene-image]
verify_jwt = false

[functions.edit-scene-image]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.wavespeed-video]
verify_jwt = false

[functions.generate-scene-dialogue]
verify_jwt = false

[functions.openai-tts]
verify_jwt = false

[functions.generate-reel-script]
verify_jwt = false

[functions.generate-reel-voiceover]
verify_jwt = false

[functions.generate-reel-video]
verify_jwt = false

[functions.creatomate-stitch]
verify_jwt = false

[functions.creatomate-status]
verify_jwt = false

[functions.merge-audio]
verify_jwt = false

[functions.migrate-images-to-storage]
verify_jwt = true

[functions.analyze-reference-image]
verify_jwt = false

[functions.analyze-face-similarity]
verify_jwt = false

[functions.clone-voice]
verify_jwt = false

[functions.clone-voice-speechify]
verify_jwt = false

[functions.upscale-video]
verify_jwt = false

[functions.ai]
verify_jwt = false

[functions.pete-ai-chat]
verify_jwt = false

[functions.analyze-face-description]
verify_jwt = false

[functions.migrate-twin-images]
verify_jwt = true

[functions.upscale-image]
verify_jwt = false

[functions.describe-scene]
verify_jwt = false
