// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asxzygexhwekvwyxjeqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeHp5Z2V4aHdla3Z3eXhqZXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDQ3NDksImV4cCI6MjA3MTQ4MDc0OX0.7QPhsakDMNPOmGqRbP839UeYPhrFFjY6zp2jjNP6oyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});